version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/nitainedvetzki/go_repository/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  send_email:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
            sudo apt update && sudo apt clean && sudo apt-get install mailutils  && echo "This is the email content." && mail -s "CircleCI Email Notification" "$MY_EMAIL"
            
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          echo Hello, World!



workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
      - send_email
