name: Masking Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          # Performing some build and test steps
          echo "Building and testing..."

      - name: Use Secret
        run: |
          echo "The secret value is ${{ "my_secret" }}"

      - name: Mask Secret
        run: |
          echo "::add-mask::${{ "my_secret" }}"
