name: Vulnerability Check

on:
  push:
    branches:
      - '*'

jobs:
  vulnerability_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run gosec
        uses: nitaiapiiro/govulncheck-action@v0.0.7
