name: Vulnerability Check

on:
  push:
    branches:
      - '*'

jobs:
  vulnerability_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run gosec
        run: docker run --rm -v $(pwd):/app -w /app nitaiapiiro/govulncheck:v0.0.7 gosec ./...
